version: '3.9'
services:
  auth-service:
    build:
      context: ./services/auth
    env_file:
      - ./services/auth/.env.example
    ports:
      - '4000:4000'

  gateway:
    build:
      context: ./services/gateway
    env_file:
      - ./services/gateway/.env.example
    ports:
      - '3000:3000'
    depends_on:
      - auth-service

  patient-service:
    build:
      context: ./services/patient
    env_file:
      - ./services/patient/.env.example
    ports:
      - '3001:3000'
    depends_on:
      - auth-service

  clinical-charting-service:
    build:
      context: ./services/clinical-charting
    env_file:
      - ./services/clinical-charting/.env.example
    ports:
      - '3002:3000'
    depends_on:
      - auth-service